name: Release to NPM

on:
  push:
      tags:
          - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Authenticate With NPM 
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc
    - name: Install node_modules
      run: npm ci
    - name: Build
      run: npm run build
    - name: Release
      run: npm publish