name: Release to NPM

on:
  push:
      tags:
          - v0.*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Fetch Git tags
      run: git fetch --prune --unshallow --tags
    - name: Authenticate With NPM 
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc
    - name: Install or fail node_modules
      run: npm ci
    - name: Build
      run: npm run build
    - name: Update package version
      run: npm --no-git-tag-version version from-git
    - name: Release
      run: npm publish