name: Test JS
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.lock') }}
        node-version: '15'
    - name: Install modules
      run: npm install
    - name: Run Jest tests
      run: npm t